name: Test Node.js App

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualiza a la versión 3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Actualiza a la versión 3
      with:
        node-version: 14 

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
